### PR TITLE
merge develop and new ifi support

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Merges https://github.com/NOAA-EMC/UPP/pull/536 into RRFS_dev

That gives us a few months of updates from develop and the latest ifi, which is still under review but should be merged soon.

Differences between this and the ifi pull request branch where `---` is the ifi branch and `+++` is this PR:

```diff
diff --git a/parm/fv3lam_rrfs.xml b/parm/fv3lam_rrfs.xml
index d5b68a9..fd384ad 100755
--- a/parm/fv3lam_rrfs.xml
+++ b/parm/fv3lam_rrfs.xml
@@ -1790,7 +1790,7 @@
        <param>
        <shortname>VIL_ON_ENTIRE_ATMOS</shortname>
        <pname>VIL</pname>
-       <scale>4.0</scale>
+       <scale>7.0</scale>
        </param>

        <param>
diff --git a/parm/postxconfig-NT-fv3lam_rrfs.txt b/parm/postxconfig-NT-fv3lam_rrfs.txt
index 938481e..48c9423 100644
--- a/parm/postxconfig-NT-fv3lam_rrfs.txt
+++ b/parm/postxconfig-NT-fv3lam_rrfs.txt
@@ -9742,7 +9742,7 @@ entire_atmos_single_lyr
 0
 0.0
 1
-4.0
+7.0
 0
 0
 0
diff --git a/sorc/ncep_post.fd/CLDRAD.f b/sorc/ncep_post.fd/CLDRAD.f
index 58bf95e..c506228 100644
--- a/sorc/ncep_post.fd/CLDRAD.f
+++ b/sorc/ncep_post.fd/CLDRAD.f
@@ -2098,11 +2098,18 @@ snow_check:   IF (QQS(I,J,L)>=QCLDmin) THEN
 !    However, for RAPv5/HRRRv4, paramater 711 will be supplied as
 !    the GSD cloud-base height, and parameter 798 will be the
 !    corresponding cloud-base pressure. (J. Kenyon, 4 Nov 2019)
+! -- E. James, 15 Dec 2022
+!    The above experimental diagnostic, developed for the HRRR with
+!    lots of "add-ons" to correct for the HRRR's low bias in cloud
+!    cover, needs to be revised for the RRFS with its more extensive
+!    cloudiness.  For an FAA deliverable due Feb 2023, the diagnostic
+!    is being modified to get rid of some of the add ons.

 !    Parameters 711/798: experimental ceiling diagnostic #2 (height and pressure, respectively)
         IF ((IGET(711)>0) .OR. (IGET(798)>0)) THEN
           ! set minimum cloud fraction to represent a ceiling
-          ceiling_thresh_cldfra = 0.4
+!          ceiling_thresh_cldfra = 0.4
+          ceiling_thresh_cldfra = 0.5
           ! set some constants for ceiling adjustment in snow (retained from legacy algorithm, also in calvis.f)
           rhoice = 970.
           coeffp = 10.36
@@ -2192,23 +2199,24 @@ snow_check:   IF (QQS(I,J,L)>=QCLDmin) THEN
                 end do
                 !-- end of search 2

-                zceil = min(zceil1,zceil2) ! choose lower of zceil1 and zceil2
+!                zceil = min(zceil1,zceil2) ! choose lower of zceil1 and zceil2
+                zceil = zceil1
                 !-- Search for "indefinite ceiling" (vertical visibility) conditions:  consider
                 ! lowering of apparent ceiling due to falling snow (retained from legacy
                 ! diagnostic); this is extracted from calvis.f (visibility diagnostic)
-                if (QQS(i,j,LM)>1.e-10) then
-                  TV=T(I,J,lm)*(H1+D608*Q(I,J,lm))
-                  RHOAIR=PMID(I,J,lm)/(RD*TV)
-                  vovermd = (1.+Q(i,j,LM))/rhoair + QQS(i,j,LM)/rhoice
-                  concfp = QQS(i,j,LM)/vovermd*1000.
-                  betav = coeffp*concfp**exponfp + 1.e-10
-                  vertvis = 1000.*min(90., const1/betav)
-                  if (vertvis < zceil-FIS(I,J)*GI ) then ! if vertvis is more restictive than zceil found above; set zceil to vertvis
-                    ! note that FIS is geopotential of the surface (ground), and GI is 1/g
-                    zceil = FIS(I,J)*GI + vertvis
-                  end if
-                end if
+!                if (QQS(i,j,LM)>1.e-10) then
+!                  TV=T(I,J,lm)*(H1+D608*Q(I,J,lm))
+!                  RHOAIR=PMID(I,J,lm)/(RD*TV)
+!                  vovermd = (1.+Q(i,j,LM))/rhoair + QQS(i,j,LM)/rhoice
+!                  concfp = QQS(i,j,LM)/vovermd*1000.
+!                  betav = coeffp*concfp**exponfp + 1.e-10
+!                  vertvis = 1000.*min(90., const1/betav)
+!                  if (vertvis < zceil-FIS(I,J)*GI ) then ! if vertvis is more restictive than zceil found above; set zceil to vertvis
+!                    ! note that FIS is geopotential of the surface (ground), and GI is 1/g
+!                    zceil = FIS(I,J)*GI + vertvis
+!                  end if
+!                end if

                 ceil(I,J) = zceil
             ENDDO      ! i loop
diff --git a/sorc/ncep_post.fd/INITPOST_NETCDF.f b/sorc/ncep_post.fd/INITPOST_NETCDF.f
index 046753a..474e351 100644
--- a/sorc/ncep_post.fd/INITPOST_NETCDF.f
+++ b/sorc/ncep_post.fd/INITPOST_NETCDF.f
@@ -889,7 +889,7 @@
         call read_netcdf_3d_para(ncid3d,im,jm,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u, &
         spval,VarName,cfr(ista_2l,jsta_2l,1),lm)
       else
-        VarName='cldfra'
+        VarName='cldfra_bl'
         call read_netcdf_3d_para(ncid2d,im,jm,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u, &
         spval,VarName,cfr(ista_2l,jsta_2l,1),lm)
       endif
```

### CODE REVIEW

**Comment by EricJames-NOAA** [comment]
@SamuelTrahanNOAA I ran a test case (on Jet) and I see the IFI fields are all undefined.  I tried to compile after setting this line in compile_upp:

ifi_opt=" -DBUILD_WITH_IFI=ON"

I see these error messages when I run compile_upp:

CMake Warning at CMakeLists.txt:78 (find_package):
  By not providing "FindIFI.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "IFI", but
  CMake did not find one.

  Could not find a package configuration file provided by "IFI" with any of
  the following names:

    IFIConfig.cmake
    ifi-config.cmake

  Add the installation prefix of "IFI" to CMAKE_PREFIX_PATH or set "IFI_DIR"
  to a directory containing one of the above files.  If "IFI" provides a
  separate development package or SDK, be sure it has been installed.

What am I doing wrong?

**Comment by SamuelTrahanNOAA** [comment]
Well, it's good to know that aspect of the build system is working properly. If you use `-DBUILD_WITH_IFI=ON` then it will build with IFI *if it can find IFI*. When the post builds without IFI, the IFI fields will be filled with missing values. Thank you for testing that!

You can force the post build system to fail if it doesn't have IFI by using `-DREQUIRE_IFI=ON`

To build with IFI, you need to be a member of the "ifi" group on Hera or Jet. The rtrr account is a member, so if you have access to that account, that's the quickest way to test. Otherwise, use AIM to request ifi access and you'll get it before too long.

**Comment by EricJames-NOAA** [comment]
@SamuelTrahanNOAA I am a member of the IFI group on Jet, so I'm not sure why it won't build with IFI:

[Eric.James@fe4 xml]$ groups
nrtrr rtruc amb-verif rucdev wrfruc rtrr rtamb rtwbl ifi rtwrfruc
[Eric.James@fe4 xml]$ whoami
Eric.James

**Comment by SamuelTrahanNOAA** [comment]
I think I see what you did. You need to revert your changes to compile_upp.sh and then run it like this:

./compile_upp.sh -i -v

It should either build with IFI or fail to build.

**Comment by EricJames-NOAA** [comment]
> I think I see what you did. You need to revert your changes to compile_upp.sh and then run it like this:
> 
> ./compile_upp.sh -i -v
> 
> It should either build with IFI or fail to build.

I did that, and it fails to build with the same error message I provided before.  Can you give me instructions on how to build it so that IFI fields are output?  I ought to be able to build it with IFI since I'm in group ifi, right?

**Comment by SamuelTrahanNOAA** [comment]
I need to see the directory in which you built, and the logs of everything that came out of cmake.

**Comment by EricJames-NOAA** [comment]
> I need to see the directory in which you built, and the logs of everything that came out of cmake.

I saved the output from running ./compile_upp.sh -i -v:

/lfs4/BMC/wrfruc/ejames/coding/UPP/tests/output.log

**Comment by hu5970** [comment]
I am compiling this branch with rtrr account:

In /mnt/lfs4/BMC/nrtrr/NCO_dirs/test/upp/UPP_GSL_sam/tests
run:
./compile_upp.sh -i

I changed the IFI lib in UPP_GSL_sam/modulefiles/jet:
 module use /lfs4/BMC/ifi/modulefiles
-module try-load ifi/20220901-intel-18.0.5.274
+module load ifi/20230118-intel-2022.1.2

But got this error message:

[100%] Linking Fortran executable upp.x
/lfs4/BMC/ifi/soft/ifi/20230118-intel-2022.1.2/lib/libIFI.so: undefined reference to `for_stop_core_quiet'
make[2]: *** [sorc/ncep_post.fd/upp.x] Error 1
make[1]: *** [sorc/ncep_post.fd/CMakeFiles/upp.x.dir/all] Error 2

**Comment by SamuelTrahanNOAA** [comment]
@hu5970 You are using the wrong compiler. The libIFI you selected is for Intel 2022.1.2, but the rest of the post is using 18.0.5.274

**Comment by SamuelTrahanNOAA** [comment]
@EricJames-NOAA Do this on Jet and tell me what you see:

```
module use /lfs4/BMC/ifi/modulefiles/
module load ifi/20230118-intel-18.0.5.274
ls $IFI_DIR
```

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do this on Jet and tell me what you see:
> 
> ```
> module use /lfs4/BMC/ifi/modulefiles/
> module load ifi/20230118-intel-18.0.5.274
> ls $IFI_DIR
> ```

[Eric.James@fe4 tests]$ module use /lfs4/BMC/ifi/modulefiles/
[Eric.James@fe4 tests]$ module load ifi/20230118-intel-18.0.5.274
[Eric.James@fe4 tests]$ ls $IFI_DIR
IFIConfig.cmake  bin  include  lib

**Comment by hu5970** [comment]
UPP can be compile using 20230118-intel-18.0.5.274.

**Comment by SamuelTrahanNOAA** [comment]
The module versions were out of date. I just updated them. Please try again.

**Comment by EricJames-NOAA** [comment]
@SamuelTrahanNOAA OK now I get a crash in UPP, looks like it is related to IFI:

/lfs4/BMC/wrfruc/ejames/RRFS/ptmp/com/logs/RRFS_CONUS/RRFS_conus_3km.20221129/15/run_post_f003_2022112915.log

**Comment by SamuelTrahanNOAA** [comment]
That is the exact error I saw before I updated the library in the ifi branch.

**Comment by SamuelTrahanNOAA** [comment]
Please recompile and try again. I'm certain the libraries are right this time because I deleted my working directory and the installed libraries, cloned again, and recompiled the libraries.

**Comment by hu5970** [comment]
I can compile and run through with this PR. But there are couple of small differences between this PR and the RRFS UPP. 
We can discuss those differences when Eric gets his case done. 
Thanks,
Ming

**Comment by EricJames-NOAA** [comment]
@SamuelTrahanNOAA I'm still getting a crash.  Is there some simple way I can test if the libraries are right in my setup?

**Comment by SamuelTrahanNOAA** [comment]
At this point, I think I need to reproduce your failing test case to make any progress in fixing this.

**Comment by hu5970** [comment]
@EricJames-NOAA  Did you use standalone UPP or you put it under ufs APP to compile and run?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Did you use standalone UPP or you put it under ufs APP to compile and run?

I compiled standalone UPP, but then copied into ufs APP directory for my test setup.  Here's the compile directory:

/lfs4/BMC/wrfruc/ejames/coding/UPP

**Comment by SamuelTrahanNOAA** [comment]
You may be using the old IGET numbers if you used the app to run it.

**Comment by hu5970** [comment]
@EricJames-NOAA  In your test, the old IFI lib was used:
            37) ifi/20220906-intel-18.0.5.274

You need to update the IFI for running:
/mnt/lfs4/BMC/wrfruc/ejames/coding/gsl-srweather-app/env/build_jet_intel.env

module use /lfs4/BMC/ifi/modulefiles
module load ifi/20220906-intel-18.0.5.274


You need to change to use the same IFI lib used for compiling:
ifi/20230118-intel-18.0.5.274

**Comment by EricJames-NOAA** [comment]
@hu5970 thanks catching that!  My test is finished, the output looks identical except for a few additional fields which have been added to EMC develop branch.  The IFI fields are slightly different, but it sounds like that is expected.

**Comment by SamuelTrahanNOAA** [comment]
Can one of you do the necessary PR to the workflow to update its modules, xml, and txt?

**Comment by EricJames-NOAA** [comment]
> Can one of you do the necessary PR to the workflow to update its modules, xml, and txt?

Yes I can do that!

**Comment by SamuelTrahanNOAA** [comment]
Is this PR ready to be merged? Or are we waiting for something still?

**Comment by EricJames-NOAA** [comment]
> Is this PR ready to be merged? Or are we waiting for something still?

Should we wait for the EMC develop PR to be merged to make sure they are consistent?  Sounds like that PR may be almost ready for merging too.

@hu5970 may have had some things he wanted to discuss too.

**Comment by SamuelTrahanNOAA** [comment]
> Should we wait for the EMC develop PR to be merged to make sure they are consistent? Sounds like that PR may be almost ready for merging too.

Right, yes, I forgot that I just added a fix to that one which I haven't merged here yet.

Perhaps we should wait until the other PR is merged first. Yes.

**Comment by SamuelTrahanNOAA** [comment]
I just removed a redundant loop that two people found.

**Comment by hu5970** [comment]
My test shows all fields from this PR are good. But my test shows some differences in grib2 table information:

1) 2n record in nat file: CLMR becomes CLWMR (no this name in grib2 table).
2) 18 record in nat file: 
Old: MASSDEN Mass Density (Concentration) [kg/m^3]:aerosol=Particulate Organic Matter Dry::
New: MASSDEN Mass Density (Concentration) [kg/m^3]:chemical=Particulate Organic Matter Dry:aerosol_size ??? code_table_4.91=255:aerosol_wavelength ??? code_table_4.91=255
3) 
New (record 1304):5000-2000 m above ground:0-1 hour min fcst:var discipline=0 center=7 local_table=1 parmcat=7 parm=200
Old (record 1303): 5000-2000 m above ground:0-1 hour min fcst:MNUPHL Hourly Minimum of Updraft Helicity [m^2/s^2]:
4) 

Old( reocrd 1529): NLAT Latitude (-90 to 90) [deg]:
New(record 1529): NLAT Latitude (-90 to 90) [&#176]

5): record 1537 and beyond:
New: var discipline=3 center=7 local_table=1 parmcat=192 parm=20
Old:  SBTA168 Simulated Brightness Temperature for ABI GOES-16, Band-8 [K]:


Those are cause by grib2 table or definition in control (NT) files. Could we double check if those differences are intended?

**Comment by SamuelTrahanNOAA** [comment]
The tables match EMC develop, except for adding the ifi fields, and changing the precision of VIL_ON_ENTIRE_ATMOS.

**Comment by EricJames-NOAA** [comment]
@hu5970 are these differences from comparing Sam's branch with EMC develop?  I don't see any differences when I compare Sam's branch with our realtime GRIB2 files, for example this file:

~rtrr/rrfs/v0.3.2/stmp/2023011917/postprd/RRFS_CONUS.t17z.bgrd3df001.tm00.grib2

**Comment by hu5970** [comment]
@EricJames-NOAA Those are difference between Sam's executable and real-time executable. Also, the NT file for Sam's code was changed to one in PR. Let me try another run with old NT file.

**Comment by hu5970** [comment]
I was using wrong executable to run the test. Now, everything looks good. Please merge the PR.

**Comment by hu5970** [comment]
@EricJames-NOAA Please update the workflow to use this new UPP.

**Review by hu5970 — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
I have merged it. Eric will need to check the latest RRFS_dev branch head to get the hash.
